finalec:
  
  joint_state_controller: 
    type: joint_state_controller/JointStateController
    publish_rate: 50
  
  c1: 
    type: effort_controllers/JointPositionController
    joint: j1  
    pid : {p: 10.0 , i: 1.0 , d: 1.0}  # Enter your pid values eg. {p: 100.0 , i: 0.0 , d: 0.0} 
    
  # Controller 2
  c2:
    type: effort_controllers/JointPositionController
    joint: j2  
    pid : {p: 10.0 , i: 1.0 , d: 2.0}  # Enter your pid values eg. {p: 100.0 , i: 0.0 , d: 0.0} 
    
  # Controller 3
  c3:
    type: effort_controllers/JointPositionController
    joint: j3 
    pid : {p: 10.0 , i: 1.0 , d: 0.0}  # Enter your pid values eg. {p: 100.0 , i: 0.0 , d: 0.0} 
    
  c4: 
    type: effort_controllers/JointPositionController
    joint: j4  
    pid : {p: 10.0 , i: 1.0 , d: 0.0}  # Enter your pid values eg. {p: 100.0 , i: 0.0 , d: 0.0} 
    
  # Controller 2
  c5:
    type: effort_controllers/JointPositionController
    joint: j5  
    pid : {p: 10.0 , i: 1.0 , d: 0.0}  # Enter your pid values eg. {p: 100.0 , i: 0.0 , d: 0.0} 
    
    

